export const teamNames = [
  "Buffer",
  "Atlanta Hawks",
  "Boston Celtics",
  "Brooklyn Nets",
  "Charlotte Hornets",
  "Chicago Bulls",
  "Clebeland Cavaliers",
  "Dallas Mavericks",
  "Denver Nuggets",
  "Detroit Pistons",
  "Golden State",
  "Houston Rockets",
  "Indianna Pacers",
  "La Clippers",
  "La Lakers",
  "Memphis Grizzlies",
  "Miami Heat",
  "Milwaukee Bucks",
  "Minnesota timberwolves",
  "New Orleans Pelicans",
  "NY Knicks",
  "OKC",
  "Orlando Magic",
  "76",
  "Suns",
  "Blazers",
  "Kings",
  "spurs",
  "raptors",
  "Jazz",
  "Wizards",
];
